version: '3.1'

networks:
  network-zabbix:
    driver: bridge

services:
  postgres-zabbix:
    container_name: postgres-zabbix
    image: postgres:13
    networks:
      - network-zabbix
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pass
    volumes:
      - pgdata:/var/lib/postgresql/data

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-pgsql:alpine-7.2-latest
    networks:
      - network-zabbix
    depends_on:
      - postgres-zabbix
    restart: always
    ports:
      - '10051:10051'
    volumes:
      - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
    environment:
      DB_SERVER_HOST: postgres-zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pass

  zabbix-frontend:
    container_name: zabbix-frontend
    image: zabbix/zabbix-web-nginx-pgsql:alpine-7.2-latest
    networks:
      - network-zabbix
    depends_on:
      - postgres-zabbix
      - zabbix-server
    links:
      - zabbix-agent
    restart: always
    ports:
      - '8080:8080'
    environment:
      DB_SERVER_HOST: postgres-zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_pass
      ZBX_SERVER_NAME: Servidor Zabbix
      PHP_TZ: America/Sao_Paulo

  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2:latest
    user: root
    networks:
      - network-zabbix
    restart: always
    privileged: true
    volumes:
      - /var/run:/var/run
    ports:
      - '10050:10050'
    environment:
      ZBX_HOSTNAME: Zabbix server
      ZBX_SERVER_HOST: zabbix-server

  debug:
    container_name: debug-x
    image: busybox
    command: tail -f /dev/null
    networks:
      - network-zabbix


volumes:
  pgdata: {}
  zbx_server_data: {}
