version: '3.8'

networks:
  zabbix-network:
    driver: bridge

services:
  mysql:
    container_name: mysql
    image: mysql:8.0
    networks:
      - zabbix-network
    ports:
      - '3306:3306'
    volumes:
      - './zabbix/mysql:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: carryontech
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: carryontech

  zabbix-server:
    container_name: zabbix-server
    image: zabbix/zabbix-server-mysql:alpine-6.0-latest
    networks:
      - zabbix-network
    depends_on:
      - mysql
    ports:
      - '10051:10051'
    volumes:
      - './zabbix/alertscripts:/usr/lib/zabbix/alertscripts'
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: carryontech

  zabbix-web:
    container_name: zabbix-web
    image: zabbix/zabbix-web-nginx-mysql:alpine-6.0-latest
    networks:
      - zabbix-network
    depends_on:
      - mysql
      - zabbix-server
    ports:
      - '8080:8080'
      - '8443:8443'
    environment:
      DB_SERVER_HOST: mysql
      MYSQL_DATABASE: zabbix
      MYSQL_USER: zabbix
      MYSQL_PASSWORD: carryontech
      PHP_TZ: America/Sao_Paulo

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    networks:
      - zabbix-network
    depends_on:
      - zabbix-server
    ports:
      - '3000:3000'
    environment:
      GF_INSTALL_PLUGINS: alexanderzobnin-zabbix-app
    volumes:
      - './grafana:/var/lib/grafana'

  zabbix-agent:
    container_name: zabbix-agent
    image: zabbix/zabbix-agent2:alpine-6.0-latest
    networks:
      - zabbix-network
    depends_on:
      - zabbix-server
    ports:
      - '10050:10050'
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_HOSTNAME: Zabbix agent
    volumes:
      - '/var/run:/var/run'
    privileged: true
