version: '3.9'

services:
  postgres-server:
    image: postgres:15
    container_name: zabbix-postgres
    environment:
      POSTGRES_DB: zabbix
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_password
    volumes:
      - zabbix_postgres_data:/var/lib/postgresql/data
    networks:
      - zabbix-net

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:alpine-7.2-latest
    container_name: zabbix-server
    environment:
      DB_SERVER_HOST: postgres-server
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_password
      ZBX_LOAD_MODULE_PATH: /var/lib/zabbix/modules
    depends_on:
      - postgres-server
    volumes:
      - zabbix_server_data:/var/lib/zabbix
    networks:
      - zabbix-net

  zabbix-frontend:
    image: zabbix/zabbix-web-nginx-pgsql:alpine-7.2-latest
    container_name: zabbix-frontend
    environment:
      DB_SERVER_HOST: postgres-server
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_password
      PHP_TZ: America/Sao_Paulo
    depends_on:
      - zabbix-server
    ports:
      - "8080:8080"
    networks:
      - zabbix-net

  zabbix-agent2:
    image: zabbix/zabbix-agent2:alpine-7.2-latest
    container_name: zabbix-agent2
    environment:
      ZBX_HOSTNAME: zabbix-agent2
      ZBX_SERVER_HOST: zabbix-server
    depends_on:
      - zabbix-server
    networks:
      - zabbix-net

volumes:
  zabbix_postgres_data:
  zabbix_server_data:

networks:
  zabbix-net:
